module.exports = ADMIN_MESSAGE_CODE = {
	ADMIN_ADDED: 201,
	GET_DETAIL_SUCCESSFULLY: 202,
    LOGGED_IN_SUCCESSFULLY: 203,
    LOGGED_OUT_SUCCESSFULLY: 204,
	ADMIN_LIST_SUCCESSFULLY: 205,
	UPDATED_SUCCESSFULLY: 206,
	ADMIN_DELETED_SUCCESSFULLY: 207
}

module.exports = USER_MESSAGE_CODE = {
	USER_REGISTARTION: 303,
	LOGIN_SUCCESSFULLY: 304,
	UPDATED_SUCCESSFULLY: 305,
	USER_DETAIL_SUCCEED:306,
	USER_LIST_SUCCESSFULLY: 307,
	OTP_SENT_SUCCESSFULLY: 308,
	OTP_VERIFY_SUCCESSFULLY:309,
	PASSWORD_SAVED: 310,
	USER_APPROVED:311,
	USER_DELETED_SUCCESSFULLY:312
}

module.exports = PRODUCT_MESSAGE_CODE = {
	PRODUCT_ADDED: 601,
	PRODUCT_UPDATED: 602 ,
	PRODUCT_DELETED_SUCCESSFULLY: 603,
	PRODUCT_LIST_SUCCESSFULLY: 604
}
module.exports = SETTING_MESSAGE_CODE = {
	SETTING_LIST_SUCCESSFULLY: 701,
	SETTING_UPDATED: 702
}

module.exports = CART_MESSAGE_CODE = {
	ITEM_ADDED: 801,
	ITEM_EDIT_SUCCESFULLY: 802,
	PRODUCT_DELETED_SUCCESSFULLY: 803,
	CART_CLEARED_SUCCESSFULLY: 804
}
module.exports = ORDER_HISTORY_MESSAGE_CODE = {
	ORDER_HISTORY_LIST_SUCCESSFULLY : 901
}

module.exports = CARD_MESSAGE_CODE = {
	CARD_ADDED_SUCCESSFULLY : 1001,
	CARD_SELECTED_SUCCESSFULLY: 1002
}